### ISSUE TITLE
Is it correct that the source says 'cookieheader' twice?

### ISSUE THREAD

**Issue by jorismak** [dneustadt/DneustadtCsrfCookieBundle#3]
https://github.com/dneustadt/DneustadtCsrfCookieBundle/blob/2640428b643c4306641e8e9e1b92e9fce2ab9ec2/Service/CsrfRequestEvaluator.php#L102-L110

headers->cookieHeader :
cookies->cookieHeader

This doesn't seem correct.

----

I have - according to the README - a default route config that says `XSRF-TOKEN` for cookie-name, and `X-XSRF-TOKEN` for header name.

On a request, I _receive_ the cookie `XSRF-TOKEN`. But if I make another request with that cookie, the CSRF is still invalid.
However, if I send another request with a  _cookie_ with the name `X-XSRF-TOKEN` it works... !?

Also, by copying the value from the `XSRF-TOKEN` cookie and specifying it in a 'X-XSRF-TOKEN' header, it works.
But this means copying the cookie to a header, which means accessing it from JavaScript which means no 'cookie.httponly'.

Also, when I reply with a _cookie_ with `X-XSRF-TOKEN` I now receive _three_ cookies. The session-cookie, a `XSRF-TOKEN` cookie _and_ a `X-XSRF-TOKEN` cookie. Something is acting up :).

Quick fix for me is to alter the default-route config to set both 'headername' and 'cookiename' to `XSRF-TOKEN`.
Now, when I receive a cookie `XSRF-TOKEN` it works when I reply with that exact same cookie.

Which means on JavaScript-side I don't have to code anything, cookies are handled by the browser, and now the cookie-settings can be set back to 'httponly' and 'secure' as it should be.

**Comment by dneustadt** [comment]
It really depends on the client-side http client you're using. Axios for example will by default see the cookie called `XSRF-Token` and add a `X-XSRF-TOKEN` header in subsequent requests. This is a de facto standard naming convention if you will. The check for a token within the request's cookies was only added as a fallback and since it was part of a previous issue #2.
If your client-side http client doesn't do so automatically you would ideally want to set the http header yourself for subsequent requests. Basically before every request check for the `XSRF-Token` and set the `X-XSRF-TOKEN` header manually. This is the behaviour that was inherited by this bundle's predecessor [DunglasAngularCsrfBundle](https://github.com/dunglas/DunglasAngularCsrfBundle). However if naming both cookie and header options the same works for you, then I don't see a reason to change anything since that is exactly what the config is for.
