### ISSUE TITLE
It creates new token everytime!!

### ISSUE THREAD

**Issue by arunvar008** [dneustadt/DneustadtCsrfCookieBundle#7]
Hello Team,

nice to see this bundle. I was trying to replace dunglas/angular-csrf-bundle with your bundle. I see the dunglas bundle refreshed csrf token only when it expired. Otherwise, it uses the same token for the next request too. Is it possible to have an option to be added to create only token, when it expired instead of creating a token every time when we hit the set token url?

Thanks,
Arun Varghese

**Comment by dneustadt** [comment]
Sorry for the long wait. This bundle fell to the wayside as I don't use it in production anymore and only now dusted it to test it with Symfony 6. 

I don't think it's really necessary to check if the current token is still valid. I would say always creating a new token on a corresponding request is a choice by design. I don't see the downside of it and most importantly, by requesting a route that creates a token, you would expect it to push the lifetime of the token as well. If you were to check if the last token was still valid and don't return a new one, then that token would eventually expire, which in turn should really be avoided by frequently requesting a new token.
